Repository Significant-Gravitas/hackathon, pull requests merged in 2023-10, with the labels that each got.

#1 feat: add node.js to hackathon.yml
  .github/workflows/hackathon.yml
Labels: size/s

#2 feat: add SERP_API_KEY
  .github/workflows/hackathon.yml
Labels: size/xs

#3 add postgresql setup
  .github/workflows/hackathon.yml
Labels: size/s

#4 fix the postgre setup issue
  .github/workflows/hackathon.yml
Labels: size/m
